export enum ItemClass {
  Quarterstaff = 'Quarterstaves',
  TwoHandMace = 'Two Hand Maces',
  Helmets = 'Helmets',
  Shields = 'Shields',
  Sceptres = 'Sceptres',
  Daggers = 'Daggers',
  Claws = 'Claws',
  Wands = 'Wands',
  Crossbows = 'Crossbows',
  OneHandSwords = 'One Hand Swords',
  TwoHandSwords = 'Two Hand Swords',
  ThrustingSwords = 'Thrusting Swords',
  OneHandAxes = 'One Hand Axes',
  TwoHandAxes = 'Two Hand Axes',
  Staves = 'Staves',
  Bows = 'Bows',
  Axes = 'Axes',
  Jewels = 'Jewels',
  Quivers = 'Quivers',
  Gems = 'Gems',
  Relics = 'Relics',
}
